import type { Metadata } from 'next';
import { ConvexClientProvider } from './ConvexClientProvider';
import './globals.css';
import { Header } from './Header';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className=''>
				<ConvexClientProvider>
					<Header />
					{children}
				</ConvexClientProvider>
			</body>
		</html>
	);
}
